# -*- coding: utf-8 -*-
"""WEB-AP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pevRJhlo8u1SWmDndY6EI5DdPQZizCoO
"""

!pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py 
# import streamlit as st
# import pandas as pd 
# import numpy as np
# import matplotlib.pyplot as plt
# 
# st.set_option('deprecation.showPyplotGlobalUse', False)
# 
# st.sidebar.title("ISSO É UM TESTE")
# 
# st.title("Análise estatística")
# 
# # Adicionando o selectbox à sidebar
# st.sidebar.title("TESTE")
# opcoes = ['BB - Fechou Fora, Fechou Dentro', 'Canal de Keltner', 'Cão Farejador', 'Cruzamento Di+ Di-', 'Cruzamento MMA 17x34', 'Dave Landry', 
# 'Estocástico Lento 70x30', 'Estocástico Lento 80x20', 'Gambitti', 'Gasparini', 'HiLo 7 períodos', 'IFR2 (Larry Connors)', 
# 'IFR2 com filtro IFR14', 'IFR4 (Larry Connors)', 'InsideBar', 'Joe Biden (com filtro MMA 20)', 'Joe Biden (sem filtros)', 
# 'Linha das sombras', 'Máximas e Mínimas', 'Medias 3 min/max ( Larry Williams)', 'Perdigão', 'Preço de Fechamento de Reversão', 
# 'Sistema MMA 9', 'Stop ATR 10 períodos', 'Terminator (Larry Connors)', 'Tik Tok (com filtro)', 'TikTok', 'Turtle' ]
# opcao_selecionada = st.sidebar.selectbox("Escolha uma opção:", opcoes)
# 
# st.sidebar.title("Time Frame")
# time_frame = st.sidebar.selectbox("Escolha o Time Frame", ["Diário", "60 m"])
# 
# # Adicionando campos de data
# st.sidebar.title("Período")
# data_inicio = st.sidebar.date_input("Data início")
# data_fim = st.sidebar.date_input("Data término")
#

!streamlit run app.py & npx localtunnel --port 8501

